In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
%reload_ext autoreload

In [3]:
from align import (
    NeedlemanWunsch,
    read_fasta)
import numpy as np
from typing import Tuple

In [4]:
seq1, h1 = read_fasta("./data/test_seq1.fa")
seq2, h2 = read_fasta("./data/test_seq2.fa")
seq3, h3 = read_fasta("./data/test_seq3.fa")
seq4, h4 = read_fasta("./data/test_seq4.fa")

print(h1, h2, h3, h4)
seq1, seq2, seq3, seq4

>test seq 1 >test seq 2 >test seq 3 >test seq 4


('MYQR', 'MQR', 'MAVHQLIRRP', 'MQLIRHP')

In [5]:
len_seqA = len(seq1)
len_seqB = len(seq2)

In [6]:
align_matrix = np.full( (len_seqA + 1, len_seqB + 1), -np.inf)
gapA_matrix = np.full( (len_seqA + 1, len_seqB + 1), -np.inf)
gapB_matrix = np.full( (len_seqA + 1, len_seqB + 1), -np.inf)

align_matrix

array([[-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf]])

In [7]:
test_NW = NeedlemanWunsch(sub_matrix_file = "./substitution_matrices/BLOSUM62.mat", gap_open = -10, gap_extend = -1)

In [8]:
align_matrix[0, 0] = 0
gapA_matrix[:, 0] = [test_NW.gap_open + i * test_NW.gap_extend for i in range(len_seqA + 1)]
gapB_matrix[0, :] = [test_NW.gap_open + i * test_NW.gap_extend for i in range(len_seqB + 1)]

align_matrix

array([[  0., -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf]])

In [9]:
gapA_matrix

array([[-10., -inf, -inf, -inf],
       [-11., -inf, -inf, -inf],
       [-12., -inf, -inf, -inf],
       [-13., -inf, -inf, -inf],
       [-14., -inf, -inf, -inf]])

In [10]:
gapB_matrix

array([[-10., -11., -12., -13.],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf]])

In [13]:
test_NW.align('MYQR','MQR')

Align v3.2
Backtrace v2


(4.0, 'MYQR', 'M-QR')

In [ ]:
test_NW.align()

In [15]:
from main import main

In [22]:
main()

Main v6
[(3173.0, 'Gallus gallus'), (3682.0, 'Mus musculus'), (2941.0, 'Balaeniceps rex'), (3916.0, 'tursiops truncatus')]
List of species in order of most similar to human BRD2 sequence.
['tursiops truncatus', 'Mus musculus', 'Gallus gallus', 'Balaeniceps rex']
List of alignment scores and what sequence was aligned to human BRD2 sequence.
[(3916.0, 'tursiops truncatus'), (3682.0, 'Mus musculus'), (3173.0, 'Gallus gallus'), (2941.0, 'Balaeniceps rex')]
